### ISSUE TITLE
Missing intbitset.pyx in the final pypi package

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/intbitset#28]
Somehow, after the redesign of `setup.py` in d2e25524bdc4af1f2d2b23ad94ebf89914ae38d9 the `intbitset.pyx` file is no longer shipped.

**Comment by tiborsimko** [comment]
Hmm, is this due to my old setup related changes?  Have you tried to publish a pre-release on https://testpypi.python.org/pypi ?

P.S. BTW the `inveniosoftware` account does not have rights on PyPI to the `intbitset` package. You may want to add it as another owner...

**Comment by tiborsimko** [comment]
Actually the problem seems to be due to 82c1f73dc73751a7a1fa51079b9736dea9b0e250 that moved some intbitset source files without updating `MANIFEST.in` accordingly.  (Please always run `check-manifest` before releasing.)

**Comment by kaplun** [comment]
Thanks. I didn't know about the existence of `check-manifest`. Worth mentioning it in the *how to make a release* document.
