### ISSUE TITLE
intbitset v2.1.1 is gone from PyPI?

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/intbitset#33]
Zenodo have had a dependency on intbitset v2.1.1 for a long time. Now the files are gone from PyPI - what happened?

**Comment by kaplun** [comment]
Weird! I think I have not touched that release explicitly, rather just the broken 2.2.0 one. I will restore the files. (note that also inveniosoftware has now right to push to pypi).

**Comment by tiborsimko** [comment]
I have just made the old files visible on PyPI.

**Comment by kaplun** [comment]
The old versions were hidden, but the files for 2.1.1 is indeed missing. So @tiborsimko this should not fix @lnielsen issue. What is strange now is that I am not allowed to upload the source back as Pypi claims the file already exist :-S

**Comment by kaplun** [comment]
@lnielsen can't you amend to use 2.2.1? It's compatible with 2.1.1 and fixes many bugs :smile:

**Comment by tiborsimko** [comment]
@kaplun Yes, I just switched the auto-hide off.

**Comment by lnielsen** [comment]
@kaplun I will of course use the new one :-) Just, we shouldn't remove old releases.

The release is visible but the files are still missing.

**Comment by kaplun** [comment]
Yes, I don't understand how it happened. Surely I made a mistake when removing the 2.2.0 release file (which was broken). I remember I removed only one file, but maybe I was :beer: ?

**Comment by tiborsimko** [comment]
Is this closable?

**Comment by kaplun** [comment]
I think so...
