### ISSUE TITLE
Operators are returning explicitly `intbitset`

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/intbitset#42]
@pombredanne reports in #40:
[...]
there is still something not right though IMHO:

```
>>> class MySet(intbitset):
...     def __init__(self, a1, a2):
...         self.union_update(range(a1, a2))
... 
>>> a=MySet(0, 12)
>>> b=MySet(5, 15)
>>> a|b
intbitset([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
```

I would expect a MySet object instead of an intbitset.

For instance with a set:

```
class SubSet(set):
    def __init__(self, a1, a2):
        super(SubSet, self).__init__(range(a1, a2))
```

I get the right subclass:

```
>>> a=SubSet(0, 12)
>>> b=SubSet(5, 15)
>>> a|b
SubSet([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
```

[...]

Indeed this is due to the fact that the `intbitset` methods and operators explicitly return a new `intbitset` object rather than an instance of the desired class.

**Comment by pombredanne** [comment]
I do not think it is a big deal... I am fine with not subclassing but delegating instead
