### ISSUE TITLE
Remove intbitset.c

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/intbitset#5]
intbitset.c can be automatically generated from available cython used as a dependency. In case the intbitset.c can be shipped in tar packages.

**Comment by pombredanne** [comment]
let me check this out and see if I can help. Cython is a beast of its own for sure.

**Comment by pombredanne** [comment]
Ok, I will come up later this week with an experimental updated `setup.py`. The trick is to handle both  cases when:
- Cython is installed and this is a clone (where cython must be called to generate the C code), and
- this is an sdist e.g. a Pypi release and Cython is not installed (e.g which is the only case supported for now)

**Comment by pombredanne** [comment]
the wheel case is not needing anything extra, this is just a regular build from an sdist or clone with a different command.

**Comment by pombredanne** [comment]
I am fine with keeping the C in VCS. Closing this now
