### ISSUE TITLE
Release wheels on Pypi?

### ISSUE THREAD

**Issue by pombredanne** [inveniosoftware/intbitset#52]
It would be great to have pre-built wheels on Pypi.
I am vendoring some here: https://github.com/nexB/scancode-toolkit/tree/1ff61e5858186210dd8393f7ee55c20c30168369/thirdparty/prod#5e8d24996c365d3aeeb00dae4cc68e1f-b33774e5140b56add6f4011934105bb3620d4e9d and I build them with these "build loops" (on Linux, Mac and Windows through Travis and Appveyor):
- https://github.com/pombreda/thirdparty 
- https://github.com/pombreda/thirdparty-manylinux/

I would be willing to help to have this baked in this project.

**Comment by kaplun** [comment]
@pombredanne thanks a lot for this. Since you seems to have quite some experience on packaging, in case would you be available to give a try to #5?

**Comment by pombredanne** [comment]
@kaplun I (unfortunately) do have some more experience that I wish for. Let me check out #5

**Comment by pombredanne** [comment]
I am wheels ready built on the ci to push for 3.0.0. Closing this now.

**Comment by pombredanne** [comment]
See https://pypi.org/project/intbitset/3.0.0/ :tada:

**Comment by pombredanne** [comment]
with wheels for Windows, macOS and Linux for all CPython versions from 3.6 to 3.10 ;)
