### ISSUE TITLE
Setup CI for Windows and Mac

### ISSUE THREAD

**Issue by pombredanne** [inveniosoftware/intbitset#53]
It would be great to have the tests running on all supported on OSes on Travis and Appveyor.
Currently Travis runs tests only on Linux. It could run on MacOSX too... And Windows is not tested (though it runs great on both OSes).
I can help as needed.

**Comment by kaplun** [comment]
Please feel free to send a PR to implement all this extended testing. I personally do not have experience with Appveyor.

**Comment by pombredanne** [comment]
All set now with GH actions.
