### ISSUE TITLE
__init__ crashes when passing list comprehension from numpy.array object

### ISSUE THREAD

**Issue by zachmoshe** [inveniosoftware/intbitset#60]
Weird, I know...

```
arr = np.array([1,2,3,4,5])

# This works
intbitset(arr.tolist())
=> intbitset([1, 2, 3, 4, 5])

# This throws SIGSEGV
intbitset([x for x in arr])
```

Surprisingly enough, it does work if `arr` is a regular list and not `np.array`

Tested on Python 3.6.3 and 2.7.13 with intbitset==2.3.0

**Comment by ttencate** [comment]
Cross-posting from [your StackOverflow question](https://stackoverflow.com/q/49029636/14637)...

Here's something interesting:

    $ gdb python 
    ...
    (gdb) run crash.py
    ...
    Thread 1 "python" received signal SIGSEGV, Segmentation fault.
    0x00007ffff745338b in ?? () from /usr/lib/libpython3.6m.so.1.0
    (gdb) bt
    #0  0x00007ffff745338b in ?? ()
       from /usr/lib/libpython3.6m.so.1.0
    #1  0x00007ffff74a245f in ?? ()
       from /usr/lib/libpython3.6m.so.1.0
    #2  0x00007ffff73f0565 in PyList_Append ()
       from /usr/lib/libpython3.6m.so.1.0
    #3  0x00007ffff73a2580 in ?? ()
       from /usr/lib/libpython3.6m.so.1.0
    #4  0x00007ffff7404b55 in _PyCFunction_FastCallDict ()
       from /usr/lib/libpython3.6m.so.1.0
    #5  0x00007ffff740e10f in _PyObject_FastCallDict ()
       from /usr/lib/libpython3.6m.so.1.0
    #6  0x00007ffff73fc9d0 in PyFile_WriteObject ()
       from /usr/lib/libpython3.6m.so.1.0
    #7  0x00007ffff74a3d6a in PyFile_WriteString ()
       from /usr/lib/libpython3.6m.so.1.0
    #8  0x00007ffff74b2f9d in PyTraceBack_Print ()
       from /usr/lib/libpython3.6m.so.1.0
    #9  0x00007ffff7491154 in ?? ()
       from /usr/lib/libpython3.6m.so.1.0
    #10 0x00007ffff7327d14 in ?? ()
       from /usr/lib/libpython3.6m.so.1.0
    #11 0x00007ffff749136e in PyErr_Display ()
       from /usr/lib/libpython3.6m.so.1.0
    #12 0x00007ffff74c890a in ?? ()
       from /usr/lib/libpython3.6m.so.1.0
    #13 0x00007ffff7404ad0 in _PyCFunction_FastCallDict ()
       from /usr/lib/libpython3.6m.so.1.0
    #14 0x00007ffff740e10f in _PyObject_FastCallDict ()
       from /usr/lib/libpython3.6m.so.1.0
    #15 0x00007ffff7492c5b in PyErr_PrintEx ()
      3.6m.so.1.0
    #16 0x00007ffff74939d1 in PyRun_SimpleFileExFlags ()
       from /usr/lib/libpython3.6m.so.1.0
    #17 0x00007ffff748970b in Py_Main ()
       from /usr/lib/libpython3.6m.so.1.0
    #18 0x0000555555554c39 in main ()

Observe the calls to `PyErr_Display` and `PyTraceBack_Print`. It looks like Python tried to show an error, but crashed in the process. Indeed, this does not crash:

    try:
        intbitset([x for x in arr])
    except Exception as ex:
        print(repr(ex))

Rather, it outputs the following:

    ValueError('retrieving integers from rhs is impossible: invalid index to scalar variable.')

This exception is raised [here in `intbitset.__cinit__`](https://github.com/inveniosoftware/intbitset/blob/8bdb3771f125495eb32a1a7c0690d57e346dc800/intbitset/intbitset.pyx#L249). Note that [`__cinit__`](http://docs.cython.org/en/latest/src/userguide/special_methods.html) is a special Cython function.

It is raised in response to another exception, coming from [`gen_arrtype_subscript`](https://github.com/numpy/numpy/blob/1290e7fd5d40903d69733b4797f7c30ca025e1f7/numpy/core/src/multiarray/scalartypes.c.src#L3572) in numpy C code. It can be triggered by indexing a scalar like this:

    >>> import numpy as np
    >>> arr = np.array([1,2,3,4,5])
    >>> arr[0][0]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IndexError: invalid index to scalar variable.

The reason that `intbitset` triggers this exception is [this line](https://github.com/inveniosoftware/intbitset/blob/8bdb3771f125495eb32a1a7c0690d57e346dc800/intbitset/intbitset.pyx#L177):

      tuple_of_tuples = rhs and hasattr(rhs, '__getitem__') and hasattr(rhs[0], '__getitem__')

Indeed, numpy scalars (`numpy.int64` in this case) _do_ have a `__getitem__`, they just don't like it if you call it. This causes `intbitset` to incorrectly assume that it's receiving a [sequence made of tuples](http://intbitset.readthedocs.io/en/latest/#intbitset.intbitset), which triggers the call to the exception-raising `__getitem__`.

This explains why it doesn't crash if you pass a generator, `intbitset(x for x in arr)`: it doesn't have `__getitem__`, so intbitset enters a different code path. If you pass `intbitset(arr)` directly, the `tuple_of_tuples` line triggers another exception, when trying to convert `arr` to a `bool`:

    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

This exception is rather un-Pythonic of numpy (inconsistent with how lists are converted to `bool`), but that's the way it works.

So why does the `invalid index to scalar` exception cause a segfault, even though the `truth value of an array` doesn't? In fact, if I put `raise ValueError()` after it, both end up crashing, so it's clearly Undefined Behaviour going on in both cases, and pure luck that it sometimes doesn't crash.

My guess is that `intbitset` does something unexpected by raising an exception from `__cinit__`. It's not explicitly forbidden in the Cython docs, so I'm not sure how or what.

**Comment by pombredanne** [comment]
@ttencate a PR would be mucho welcomed if can provide one.

**Comment by ttencate** [comment]
@pombredanne Sorry, don't count on me, it was just some drive-by debugging. I don't even remember what project I was using intbitset for.

**Comment by pombredanne** [comment]
```
>>> import numpy as np
>>> arr = np.array([1,2,3,4,5])
>>> [x for x in arr]
[1, 2, 3, 4, 5]
>>> a=[x for x in arr]
>>> type(a[0])
<class 'numpy.int64'>
>>> from intbitset import intbitset
>>> intbitset([int(x) for x in arr])
intbitset([1, 2, 3, 4, 5])

```

we do not support the numpy.int64 type... these are not ints.... so the easy way around is to convert to integers.
```
>>> isinstance(a[0], int)
False
```

**Comment by pombredanne** [comment]
Closing for now. Thanks for your patience!
