### ISSUE TITLE
Intbitset installation fails on Python 3

### ISSUE THREAD

**Issue by Abhishek-Dev09** [inveniosoftware/intbitset#64]
Description : Intbitset failed to install on Python 3 but it is fine with Python 3.6.8

Python version - 3.7.1
OS- macOS mojave(10.14.6)
GCC - 9.1

Reference - https://github.com/nexB/scancode-toolkit/issues/1631
Goal - to add support for python 3.7.1

**Comment by greut** [comment]
https://github.com/inveniosoftware/intbitset/pull/62

**Comment by pombredanne** [comment]
I regened, merged a few things and pushed https://pypi.org/project/intbitset/2.4.0/ :)

**Comment by pombredanne** [comment]
A new release has been made.
Thank you for the report and your patience
