### ISSUE TITLE
Update PyPI auto release credentials

### ISSUE THREAD

**Issue by pombredanne** [inveniosoftware/intbitset#66]
For now @kaplun old credentials are used and they fail:
```
PyPI upload failed.
failed to deploy
```
https://travis-ci.org/inveniosoftware/intbitset/jobs/627259098#L567

**Comment by pombredanne** [comment]
For now I pushed https://pypi.org/project/intbitset/2.4.0/ by hand

**Comment by kaplun** [comment]
Hey sorry I haven't noticed this. Is there a way I can unblock you? You can write me in case at kaplun@protonmail.com

**Comment by pombredanne** [comment]
@kaplun I do not have access to the travis account so I likely cannot update the encrypted credentials there. But may be this is moot... Frankly I am not sure I like the idea of auto release from a host I do not have control on....

**Comment by kaplun** [comment]
Yeah agreed :)

**Comment by kaplun** [comment]
Actually since I am no longer maintainer of it I can't amend anything there. @lnielsen maybe you can see if you can ensure @pombredanne has proper rights over it?

**Comment by lnielsen** [comment]
@pombredanne Do you want to release it manually? If so I think you have access to the PyPI package, if not, I can make a new token using the inveniosoftware user.

**Comment by pombredanne** [comment]
@lnielsen I pushed a release by hand. In earnest I prefer it this way. I have access to the Pypi account alright. So we are fine . Let me close this! :)
